server:
port: 8189
servlet:
context-path: /spring2
spring:
datasource:
driver-class-name: org.h2.Driver
url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
username: admin1234
password:
jpa:
show-sql: true
properties:
hibernate:
dialect: org.hibernate.dialect.H2Dialect
h2:
console:
enabled: true
settings:
web-allow-others: false
